export const INIT_POSITIONS = 'INIT_POSITIONS';
export const LOAD_POSITIONS_IN_PROGRESS = 'LOAD_POSITIONS_IN_PROGRESS';
export const LOAD_POSITIONS_SUCCESS = 'LOAD_POSITIONS_SUCCESS';
export const LOAD_POSITIONS_FAILURE = 'LOAD_POSITIONS_FAILURE';

export const INIT_ADD_POSITION = 'INIT_ADD_POSITION';
export const ADD_POSITION_IN_PROGRESS = 'ADD_POSITION_IN_PROGRESS';
export const ADD_POSITION_SUCCESS = 'ADD_POSITION_SUCCESS';
export const ADD_POSITION_FAILURE = 'ADD_POSITION_FAILURE';
