export const INIT_POSITIONS = 'INIT_POSITIONS';
export const LOAD_POSITIONS_IN_PROGRESS = 'LOAD_POSITIONS_IN_PROGRESS';
export const LOAD_POSITIONS_SUCCESS = 'LOAD_POSITIONS_SUCCESS';
export const LOAD_POSITIONS_FAILURE = 'LOAD_POSITIONS_FAILURE';

export const INIT_ADD_POSITION = 'INIT_ADD_POSITION';
export const ADD_POSITION_IN_PROGRESS = 'ADD_POSITION_IN_PROGRESS';
export const ADD_POSITION_SUCCESS = 'ADD_POSITION_SUCCESS';
export const ADD_POSITION_FAILURE = 'ADD_POSITION_FAILURE';

export const INIT_WATCHLIST = 'INIT_WATCHLIST';
export const LOAD_WATCHLIST_IN_PROGRESS = 'LOAD_WATCHLIST_IN_PROGRESS';
export const LOAD_WATCHLIST_SUCCESS = 'LOAD_WATCHLIST_SUCCESS';
export const LOAD_WATCHLIST_FAILURE = 'LOAD_WATCHLIST_FAILURE';

export const INIT_ADD_WATCHLIST_ITEM = 'INIT_ADD_WATCHLIST_ITEM';
export const ADD_WATCHLIST_ITEM_IN_PROGRESS = 'ADD_WATCHLIST_ITEM_IN_PROGRESS';
export const ADD_WATCHLIST_ITEM_SUCCESS = 'ADD_WATCHLIST_ITEM_SUCCESS';
export const ADD_WATCHLIST_ITEM_FAILURE = 'ADD_WATCHLIST_ITEM_FAILURE';
